Wray_Portal_Phase1/Controllers/ChartsController.cs
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wray_Portal_Phase1.Models;
using Wray_Portal_Phase1.ViewModels;

namespace Wray_Portal_Phase1.Controllers
{
    public class ChartsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Charts
        public JsonResult GetCategoryChartData()
        {
            var colorList = new List<string>();
            colorList.Add("#886896");
            colorList.Add("#d2d6de");

            var catDataVM = new CatDataVM();
            var householdId = db.Users.Find(User.Identity.GetUserId()).HouseholdId;

            foreach (var category in db.Categories.Where(c => c.HouseholdId == householdId).ToList())
            {
                var catData = new CategoryDataVM
                {
                    Name = category.Name,
                    Target = category.TargetAmount
                };

                foreach (var item in db.Categories.Find(category.Id).CategoryItems.ToList())
                {
                    // This should be focused on the current month only!!!
                    // How do I work down the Transactions to only this month??
                    // Where(t = t.Created) is a good place to start
                    var transactions = db.Transactions.Where(t => t.CategoryItemId == item.Id).ToList();
                    if (transactions.Count > 0)
                    {
                        catData.Actual += transactions.Sum(t => t.Amount);
                    }
                }

                catDataVM.Data.Add(catData);
                catDataVM.Colors.AddRange(colorList);
            }

            catDataVM.Labels.AddRange(new List<string> { "Target", "Actual", "Name" });

            return Json(catDataVM);
        }

        public JsonResult TestCalByMonth()
        {
            var categoryItemId = 2;
            var amount = db.Transactions.Where(t => t.Created.Month == DateTime.Now.Month 
                                                                    && t.CategoryItemId == categoryItemId)
                                                                    .Sum(t => t.Amount);
            return Json(amount);
        }
    }
}

Wray_Portal_Phase1/Views/Shared/_Layout.cshtml
@using Wray_Portal_Phase1.Helper
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Budget Duck</title>

    <!-- Font Awesome Icons -->
    <link href="~/Content/all.min.css" rel="stylesheet" />

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- overlayScrollbars -->
    <link href="~/Content/OverlayScrollbars.min.css" rel="stylesheet" />

    <!-- DataTables -->
    <link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/responsive.bootstrap4.min.css" rel="stylesheet" />

    <!-- Morris Charts -->
    <link href="~/Content/morris.css" rel="stylesheet" />

    <!-- Theme style -->
    <link href="~/Content/adminlte.min.css" rel="stylesheet" />

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">



    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Images/favicon-32x32.png" />

</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-sm-footer-not-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="@Url.Action("Dashboard", "Households")" class="nav-link">Home</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-info navbar-badge"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <span class="text-muted text-uppercase text-sm">User Actions</span>
                        <i class="fas fa-user"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">User Actions</span>
                        <div class="dropdown-divider"></div>
                        <a href="@Url.Action("About", "Home")" class="dropdown-item">
                            <i class="fas fa-user mr-2"></i> Profile
                        </a>
                        <div class="dropdown-divider"></div>
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                <a href="javascript:document.getElementById('logoutForm').submit()" class="dropdown-item">
                                    <i class="fas fa-door-open mr-2"></i>Log Out
                                </a>
                            }
                        }
                    </div>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Side Nav Partial View -->
        @Html.Action("_SideNav", "Households")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-content">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer small">
            <div class="layout-sm-footer-not-fixed">
                <strong>Copyright &copy; @DateTime.Now.Year.  <a href="//ashtondwray-portfolio.azurewebsites.net/" target="_blank" class="text-orange">Ashton Wray</a>.</strong>
                All rights reserved.
            </div>
        </footer>
    </div>
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/Scripts/jquery.min.js"></script>

    <!-- Bootstrap -->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

    <!-- overlayScrollbars -->
    <script src="~/Scripts/jquery.overlayScrollbars.min.js"></script>

    <!-- bs-custom-file-input -->
    <script src="~/Scripts/bs-custom-file-input.min.js"></script>


    <!-- DataTables -->
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/dataTables.responsive.min.js"></script>
    <script src="~/Scripts/responsive.bootstrap4.min.js"></script>

    <!-- ChartJS -->
    <script src="~/Scripts/Chart.min.js"></script>

    <!-- AdminLTE App -->
    @*<script src="~/Scripts/adminlte.js"></script>*@
    <script src="~/Scripts/adminlte.min.js"></script>

    <!-- PAGE PLUGINS -->
    <!-- jQuery Mapael -->
    <script src="~/Scripts/jquery.mousewheel.js"></script>
    <script src="~/Scripts/raphael.min.js"></script>
    <script src="~/Scripts/morris.min.js"></script>
    <script src="~/Scripts/jquery.mapael.min.js"></script>
    <script src="~/Scripts/usa_states.min.js"></script>



    <!-- Sweet Alerts -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script src="//unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

    <script>
        //-------------
        //- BAR CHART -
        //-------------

        if ($('#barChart').length) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCategoryChartData", "Charts")',
                dataType: "json"
            }).then(function (response) {
                new Morris.Bar({
                    element: 'barChart',
                    data: response.Data,
                    barColors: ['#00a65a', '#f56954'],
                    xkey: 'Name',
                    ykeys: ['Target', 'Actual'],
                    labels: response.Labels
                });
            });
        };
    </script>
    <script>
        @*$.ajax({
            type: "POST",
            url: '@Url.Action("TestCalByMonth", "Charts")',
            dataType: "json"
        }).then(function () {
        });*@

        @*$.ajax({
                type: "POST",
                url: '@Url.Action("GetCategoryChartData", "Charts")',
                dataType: "json"
            }).then(function (response) {
                var barChartCanvas = $('#barChart').get(0).getContext('2d');
                var barChartData = {
                    labels: response.Labels,
                    datasets: [
                        {
                            label: 'Target',
                            backgroundColor: '#f39c12',
                            data: response.Data
                        },
                        {
                            label: 'Actual',
                            backgroundColor: '#3b42cc',
                            data: response.Data
                        }
                    ]
                };

                var barChartOptions = {
                    responsive: true,
                    maintainAspectRatio: false,
                    datasetFill: false
                };

                var barChart = new Chart(barChartCanvas, {
                    type: 'bar',
                    data: barChartData,
                    options: barChartOptions
                });
            });*@
    </script>


    <script>
        $(function () {
            $("table").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
            $("#example1").DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            bsCustomFileInput.init();
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>
 

Wray_Portal_Phase1/Views/Shared/_SideNav.cshtml
@model Wray_Portal_Phase1.Models.ApplicationUser

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-light-cyan elevation-4">
    <!-- Brand Logo -->
    <a href="@Url.Action("Dashboard", "Households")" class="brand-link">
        <span></span>
        <span class="brand-text">
            <img src="~/Images/onlinelogomaker-060220-0025-0867.png" alt="Budget Duck Logo" class="mx-4 w-75">
        </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="@Model.AvatarPath" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="@Url.Action("About", "Home")" class="d-block text-lg brand-text font-weight-light">Welcome @Model.DisplayName</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview menu-open">
                    <a href="@Url.Action("Dashboard", "Households")" class="nav-link active">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-university"></i>
                        <p>
                            Bank Accounts
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("Create", "BankAccounts")" class="nav-link">
                                <i class="fas fa-plus nav-icon"></i>
                                <p>
                                    Add Bank Account
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- None of this should be available to NewUser -->
                @if (User.IsInRole("Owner") || User.IsInRole("Member"))
                {
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-house-user"></i>
                            <p>
                                Household
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("LeaveAsync", "Households")" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Leave Household</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-university"></i>
                            <p>
                                Bank Accounts
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("Create", "BankAccounts")" class="nav-link">
                                    <i class="fas fa-plus nav-icon"></i>
                                    <p>Add Bank Account</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-layer-group"></i>
                            <p>
                                Categories
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("Create", "Categories")" class="nav-link">
                                    <i class="fas fa-plus nav-icon"></i>
                                    <p>New Category</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Create", "CategoryItems")" class="nav-link">
                                    <i class="fas fa-plus nav-icon"></i>
                                    <p>New Category Item</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="@Url.Action("Create", "Transactions")" class="nav-link">
                            <i class="fas fa-plus nav-icon"></i>
                            <p>
                                New Transactions
                            </p>
                        </a>
                    </li>
                }
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>